services:

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.5
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://kafka:9092
    ports: [ "9092:9092" ]
    networks: [ neurowatch_net ]
    healthcheck:
      test: [ "CMD", "bash", "-c", "rpk cluster info || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=neurowatch
    networks:
      - neurowatch_net
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/nw-db
    command: "mongod --quiet --logpath /dev/null "
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  neurowatch:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile${SUFFIX}
      args:
        project: neurowatch
    networks:
      - neurowatch_net
    ports:
      - "8080:8080"
    environment:
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/neurowatch
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - JAVA_TOOL_OPTIONS=-Dsun.net.inetaddr.ttl=0
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:

networks:
  neurowatch_net:
    external: true