services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-svq
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama
      - ./ollama/init:/init
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_DEBUG=2
    entrypoint: [ "/bin/sh", "/init/run_ollama.sh" ]
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=neurowatch
    networks:
      - neurowatch_net
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/nw-db
    command: "mongod --quiet --logpath /dev/null "
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  neurowatch:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile${SUFFIX}
      args:
        project: neurowatch
    networks:
      - neurowatch_net
    ports:
      - "8080:8080"
    environment:
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/neurowatch
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - JAVA_TOOL_OPTIONS=-Dsun.net.inetaddr.ttl=0
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:

networks:
  neurowatch_net:
    external: true