vaadin.launch-browser=true
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/neurowatch}
spring.data.mongodb.auto-index-creation=true

app.seed.yaml.enabled=false
app.seed.yaml.location=classpath:/seed-data.yaml
app.create-test-users=true

spring.jackson.find-and-add-modules=true

# Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1:8b
spring.ai.ollama.chat.options.temperature=0.0


logging.level.org.springframework.ai=DEBUG
logging.level.dev.cyberjar.neurowatch=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
