vaadin.launch-browser=true
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/neurowatch}
spring.data.mongodb.auto-index-creation=true
app.create-test-users=true

spring.cloud.function.definition=logConsumer
spring.cloud.stream.bindings.logConsumer-in-0.destination=neurowatch.logs.raw
spring.cloud.stream.bindings.logConsumer-in-0.group=neurowatch
spring.cloud.stream.bindings.logConsumer-in-0.consumer.useNativeDecoding=false
spring.cloud.stream.bindings.logConsumer-in-0.contentType=application/octet-stream

spring.kafka.bootstrap-servers=${KAFKA_BROKERS:kafka:9092}
spring.jackson.find-and-add-modules=true

# Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:8b
spring.ai.ollama.chat.options.temperature=0.0