vaadin.launch-browser=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=neurowatch
spring.data.mongodb.auto-index-creation=true
app.create-test-users=true

spring.cloud.function.definition=logConsumer
spring.cloud.stream.bindings.logConsumer-in-0.destination=neurowatch.logs.raw
spring.cloud.stream.bindings.logConsumer-in-0.group=neurowatch
spring.cloud.stream.bindings.logConsumer-in-0.consumer.useNativeDecoding=false
spring.cloud.stream.bindings.logConsumer-in-0.contentType=application/octet-stream

spring.kafka.bootstrap-servers=${KAFKA_BROKERS:kafka:9092}