FROM bellsoft/liberica-native-image-kit-container:jdk-25-nik-25-musl as builder
RUN apk add --no-cache nodejs npm
WORKDIR /app
ADD . /app/neurowatch
ENV SPRING_PROFILES_ACTIVE=native
RUN cd neurowatch && ./mvnw -Pproduction -Pnative -DskipTests native:compile

FROM bellsoft/alpaquita-linux-base:musl
WORKDIR /app
ENTRYPOINT ["/app/app"]
COPY --from=builder /app/neurowatch/target/native/neurowatch /app/app