FROM bellsoft/liberica-runtime-container:jdk-21.0.12_10-musl as builder
RUN apk add --no-cache nodejs npm
WORKDIR /app
ADD . /app/neurowatch
RUN cd neurowatch && ./mvnw -Pproduction clean package

FROM bellsoft/liberica-runtime-container:jre-21.0.12_11-crac-cds-stream-musl

WORKDIR /app
COPY --from=builder /app/neurowatch/target/neurowatch-*.jar app.jar
ENTRYPOINT ["java", "-XX:CRaCCheckpointTo=/app/checkpoint", "-jar", "/app/app.jar"]