FROM bellsoft/liberica-runtime-container:jdk-21-musl as builder
RUN apk add --no-cache nodejs npm
WORKDIR /app
ADD . /app/neurowatch
RUN cd neurowatch && ./mvnw -Pproduction clean package

FROM bellsoft/liberica-runtime-container:jdk-21-crac-cds-musl

WORKDIR /app
COPY --from=builder /app/neurowatch/target/neurowatch-*.jar app.jar
ENTRYPOINT ["java", "-XX:CRaCCheckpointTo=/app/checkpoint", "-XX:MaxRAMPercentage=80.0", "-jar", "/app/app.jar"]