FROM eclipse-temurin:25-jdk as builder
WORKDIR /app
COPY . /app/neurowatch
RUN cd neurowatch && ./mvnw -Pproduction -Dmaven.test.skip=true clean package

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/neurowatch/target/neurowatch-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]