FROM bellsoft/liberica-runtime-container:jdk-all-24-musl as builder
RUN apk add --no-cache nodejs npm

WORKDIR /app
ADD . /app/neurowatch
RUN cd neurowatch && ./mvnw -Pproduction clean package

RUN jlink --compress=2 --strip-debug --no-header-files \
    --no-man-pages --add-modules \
    java.base,java.compiler,java.desktop,java.instrument,java.logging,java.management,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.sql,java.transaction.xa,java.xml,jdk.attach,jdk.jdi,jdk.jfr,jdk.unsupported \
    --output /jlink-runtime

FROM bellsoft/alpaquita-linux-base:stream-musl
COPY --from=builder /jlink-runtime /jlink-runtime
COPY --from=builder /app/neurowatch/target/neurowatch-*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["/jlink-runtime/bin/java", "-jar", "app.jar"]